name: Build and publish container image

on:
  push:
    branches: [ master, '[0-9]+.[0-9]+' ]
    # Publish semver tags as releases.
    tags: [ 'v[0-9]+.[0-9]+*', 'v[0-9]+.[0-9]+.[0-9]+*' ]
  pull_request:
    branches: [ master, '[0-9]+.[0-9]+' ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      # required for access to the local publish action
      - name: Check out PeekabooAV
        uses: actions/checkout@v3
        with:
          path: actions

      - name: Work around checkout action pruning the workspace
        id: actions
        run: |
          cp -a actions/.github/actions/container-image-publish ..

      - uses: ./../container-image-publish
        with:
          ref: ${{ github.ref }}
          base-ref: ${{ github.base_ref }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
