name: Testsuite (scheduled)

on:
  workflow_dispatch:
  schedule:
    - cron: "10 1 * * 0"

jobs:
  # these may be highly redundant but actually need to be because every branch
  # might need its own build procedure as well as have different supported
  # environments, e.g. python versions. We can group closely related branches
  # through the matrix build.
  test-group-2:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        branch: ["master", "2.1"]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install aiosqlite

      - name: Run the testsuite
        run: tests/test.py

  test-group-1:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        branch: ["2.0"]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the testsuite
        run: tests/test.py
